"""add_refresh_tokens

Revision ID: 0d5d69bb9f0c
Revises: 4e72b928b64a
Create Date: 2025-04-03 18:40:24.019993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0d5d69bb9f0c'
down_revision: Union[str, None] = '4e72b928b64a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articlecontent')
    op.add_column('users', sa.Column('refresh_tokens', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires')
    op.drop_column('users', 'refresh_tokens')
    op.create_table('articlecontent',
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(), nullable=False),
    sa.Column('last_updated', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    # ### end Alembic commands ###
