"""add bloomberg latest

Revision ID: 98b24c16ffc9
Revises: d43373efe642
Create Date: 2025-02-23 11:08:41.103253

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = "98b24c16ffc9"
down_revision: Union[str, None] = "d43373efe642"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    bloomberg_source = conn.execute(
        sa.text("""
            INSERT INTO sources (
                    name,
                    feed_symbol,
                    base_url,
                    active_status,
                    fetch_interval,
                    last_fetch_time,
                    created_at,
                    updated_at
                ) VALUES (
                    'Bloomberg',
                    'BBG',
                    'https://www.bloomberg.com',
                    true,
                    300,
                    :now,
                    :now,
                    :now
                ) RETURNING id
            """),
        {"now": datetime.now()},
    ).fetchone()

    bloomberg_source_id = bloomberg_source[0]

    conn.execute(
        sa.text("""
            INSERT INTO categories(
                name,
                source_id,
                feed_url,
                created_at,
                updated_at
            ) VALUES (
                'latest',
                :source_id,
                '/lineup-next/api/stories?limit=25&pageNumber=1&types=ARTICLE,FEATURE,INTERACTIVE,LETTER,EXPLAINERS',
                :now,
                :now
            )
        """),
        {"source_id": bloomberg_source_id, "now": datetime.now()},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    conn.execute(
        sa.text("""
            DELETE FROM categories
            WHERE source_id = (
                SELECT id from sources
                WHERE feed_symbol = 'BBG'
            )
        """)
    )

    conn.execute(
        sa.text("""
            DELETE FROM sources
            WHERE feed_symbol = 'BBG'
        """)
    )
    # ### end Alembic commands ###
