"""unique_constraints

Revision ID: aba42b6741f5
Revises: e9d2e6a7e329
Create Date: 2025-04-30 14:29:21.878939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aba42b6741f5'
down_revision: Union[str, None] = 'e9d2e6a7e329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articlecategories_category_article', table_name='articlecategories')
    op.alter_column('articles', 'url_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_articles_pub_date_id', table_name='articles')
    op.drop_index('ix_articles_content_hash', table_name='articles')
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.drop_index('ix_articles_url_hash', table_name='articles')
    op.create_index(op.f('ix_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.drop_index('ix_feedpreferences_user_active_feed', table_name='feedpreferences')
    op.drop_index('ix_users_refresh_token', table_name='users', sqlite_where=sa.text('refresh_token IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_refresh_token', 'users', ['refresh_token'], unique=False, sqlite_where=sa.text('refresh_token IS NOT NULL'))
    op.create_index('ix_feedpreferences_user_active_feed', 'feedpreferences', ['user_id', 'is_active', 'feed_id'], unique=False)
    op.drop_index(op.f('ix_articles_url_hash'), table_name='articles')
    op.create_index('ix_articles_url_hash', 'articles', ['url_hash'], unique=False)
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.create_index('ix_articles_content_hash', 'articles', ['content_hash'], unique=1)
    op.create_index('ix_articles_pub_date_id', 'articles', ['pub_date', 'id'], unique=False)
    op.alter_column('articles', 'url_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('ix_articlecategories_category_article', 'articlecategories', ['category_id', 'article_id'], unique=False)
    # ### end Alembic commands ###
