"""fix_token_typo

Revision ID: ee3c2f74184f
Revises: 0d5d69bb9f0c
Create Date: 2025-04-07 17:17:32.737267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee3c2f74184f'
down_revision: Union[str, None] = '0d5d69bb9f0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'refresh_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_tokens', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
